# permissions for end users to edit sleepdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sleepdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sleepdeployment
    app.kubernetes.io/part-of: sleepdeployment
    app.kubernetes.io/managed-by: kustomize
  name: sleepdeployment-editor-role
rules:
- apiGroups:
  - kronos.demo.wecraft.tn
  resources:
  - sleepdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kronos.demo.wecraft.tn
  resources:
  - sleepdeployments/status
  verbs:
  - get
